### ISSUE TITLE
directory changed after executing from another directory

### ISSUE THREAD

**Issue by bithadder** [Qwinn1/forktools#1]
Hey, I executed the forktools from another directory that's already got venv activated and after the command runs and showed the nodes, the active directory changed.

This is what happened 
```
(venv) user@system:~/ext9-blockchain$ . ~/forktools/forknodes seno
seno show -a 77.38.4.97:18444
seno show -a 109.145.190.23:18444
seno show -a 95.163.12.167:18444
seno show -a 68.149.128.144:18444
seno show -a 87.5.224.41:18444
seno show -a 91.44.220.224:18444
seno show -a 84.178.198.80:18444
(venv) user@system:~/seno-blockchain$
```

reproduction of the issue
```
(venv) user@system:~/stor-blockchain$ . ~/forktools/forknodes seno
seno show -a 77.38.4.97:18444
seno show -a 109.145.190.23:18444
seno show -a 95.163.12.167:18444
seno show -a 68.149.128.144:18444
seno show -a 87.5.224.41:18444
seno show -a 91.44.220.224:18444
seno show -a 84.178.198.80:18444
(venv) user@system:~/seno-blockchain$ 

```

This happened with the `forknodes` command, but not some other commands like `forklogp` and `forklogh` I haven't tried other commands

**Comment by Qwinn1** [comment]
I had a hard time duplicating this, until I added the "." that you are prefacing every command with.  That period isn't necessary and not sure why you're adding it.  Leave that out and it won't change the directory on you anymore.

I'd also recommend adding forktools to your PATH as described in the environment section of the readme.  Having to retype ~/forktools/ before every command is a ton of unnecessary keystrokes, which is the main reason for these tools' existence :)

**Comment by bithadder** [comment]
that did the trick, thank you for this!
