### ISSUE TITLE
feature request : restart and farming status + number of plots for all forks

### ISSUE THREAD

**Issue by bithadder** [Qwinn1/forktools#2]
Hi, can you add a feature to 
1. restart all
2. Check farming status as well as see the number of plots 
3. configure log level
4. configure set farmer peer (for setting up from harvesters)
5. if possible do an scp of the /ca/ files to a location on the remote harvesters

for all forks inside the forkstartall list?

Thanks

**Comment by Qwinn1** [comment]
What do you mean by the "restart" portion of that?  But a more detailed version of forkcounth sounds like a good idea.

**Comment by bithadder** [comment]
sorry I pushed enter didn't  knew it would post the issue, but I've edited the description

**Comment by bithadder** [comment]
ah okay I just saw the -r parameter thing, great I'll try it, thanks

**Comment by Qwinn1** [comment]
Forkstartall.template uses forkstartf or forkstartfnw or forkstarth (you set it up per your liking, and all of those use -r parameter so you can use them again as a restart routine.

And yeah, tools for initial setup of configs is something I've been meaning to get on.  Frankly just having forkaddplotdirs made things so much easier than before that I wasn't minding doing the last few steps manually.  But yeah.  I'll also add a way to autoset log_maxfilesrotation, since that's one I always bump up to 99.

#2 will take a bit of work parsing out the results of farm summary, as I'm not sure how else to get total # of plots that include harvesters, but should be doable.

Not sure what #5 is about.  Let me work on 2, 3 and 4 and I'll get back to you on that one.

**Comment by bithadder** [comment]
I've tried restarting succesfully, previously I did forkstopall and then forkstartall like an idiot lol

for #5
To use remote harvesters, we need to copy the files within the` /.chia/ssl/ca` directory to our remote harvesters and then running `chia init -c /localcadirectory/` in order to add the ssl keys of our farmer peer to it, it's from the **Farming on Many Machines guide** on chia wiki.

I'd like to use forktools at least to do this process for the new forks with default convention, but that also means the need to `mkdir` to the remote harvester and permissions to create / copy files inside of them though, could be unnecessary complicated for the simple `scp` that I'm trying to do

so far I just use shell via mc for it

**Comment by bithadder** [comment]
for #2 I have a scriptfile that I've set up that I call `farmsummary.sh` 

which contain these kinds of one liners, I needed to add or remove them as required, but I'm sure it could be much better though as I suck in scripting
```echo 'chives'
/home/user/chives-blockchain/venv/bin/chives farm summary | grep 'Plot count\|Farming status\|Total'
echo 'seno'
/home/user/seno-blockchain/venv/bin/seno farm summary | grep 'Plot count\|Farming status\|Total'
```

**Comment by Qwinn1** [comment]
How's this?

```
qwinn@Huginn:~/forktools$ forksumall

----------------------------------------------- FARMERS ----------------------------------------------------

Fork                 Status               Plot Count      Netspace             ETW                           
------------------------------------------------------------------------------------------------------------
cactus               Farming              4424            258.247 PiB          3 hours and 4 minutes         
cryptodoge           Farming              4424            167.256 PiB          1 hour and 49 minutes         
dogechia             Farming              4424            489.015 PiB          6 hours                       
hddcoin              Farming              4424            472.153 PiB          5 hours and 24 minutes        
kale                 Farming              4424            344.015 PiB          3 hours and 15 minutes        
melati               Farming              4424            266.953 PiB          2 hours and 49 minutes        
olive                Farming              4424            87.948 PiB           1 hour and 24 minutes         
seno                 Farming              1379            344.824 PiB          13 hours and 17 minutes       
silicoin             Farming              4424            789.190 PiB          10 hours and 36 minutes       
socks                Farming              4424            293.978 PiB          3 hours and 4 minutes         
taco                 Farming              4424            320.899 PiB          3 hours and 52 minutes        
tad                  Farming              4424            297.107 PiB          3 hours and 21 minutes        

--------------------------------------------- HARVESTERS ---------------------------------------------------

Fork                 Status               Plot Count      Last Harvest Time         Last Response Time       
------------------------------------------------------------------------------------------------------------
apple                Harvesting           1379            2021-08-28T00:45:55       0.27855 s.               
avocado              Harvesting           1379            2021-08-28T00:45:51       0.29182 s.               
btcgreen             Harvesting           1379            2021-08-28T00:45:53       0.23053 s.               
cannabis             Harvesting           1379            2021-08-28T00:45:55       0.14864 s.               
chia                 Harvesting           1379            2021-08-28T00:45:53       0.53106 s.               
covid                Harvesting           1379            2021-08-28T00:45:56       0.34880 s.               
flax                 Harvesting           1379            2021-08-28T00:45:59       0.17961 s.               
flora                Harvesting           1379            2021-08-28T00:45:59       0.22925 s.               
goji                 Harvesting           1379            2021-08-28T00:45:52       0.15745 s.               
greendoge            Harvesting           1379            2021-08-28T00:45:55       0.02812 s.               
maize                Harvesting           1379            2021-08-28T00:45:54       0.14629 s.               
scam                 Harvesting           1379            2021-08-28T00:45:49       0.05360 s.               
venidium             Harvesting           1379            2021-08-28T00:45:52       0.17753 s.             
```

**Comment by bithadder** [comment]
that looks like exactly what I need, awesome!

**Comment by Qwinn1** [comment]
Gets better.

```
```
qwinn@Huginn:~/.taco/mainnet/log$ forksumall

----------------------------------------------- FARMERS ----------------------------------------------------

Fork                 Version         Status             # Peers   # Plots    Netspace       ETW     
------------------------------------------------------------------------------------------------------------
cactus               1.2.2.dev7      Farming                  8      4424     254 PiB       3h 17m    
cryptodoge           1.2.6           Farming                 19      4424     172 PiB       1h 48m    
dogechia             1.0.9           Farming                  8      4424     490 PiB       5h 58m    
hddcoin              1.2.3           Farming                 11      4424     475 PiB       5h 40m    
kale                 0.1.111         Farming                 21      4424     355 PiB       3h 58m    
melati               1.1.7140        Farming                  8      4424     270 PiB       2h 53m    
olive                0.0.296         Farming                 20      4424      91 PiB       1h 15m    
seno                 1.1.8.dev36     Farming                  8      1379     346 PiB       12h 38m   
silicoin             0.0.9.dev10     Farming                 15      4424     789 PiB       9h 30m    
socks                0.1.dev4802     Farming                  8      4424     304 PiB       3h 27m    
taco                 2.1.1.dev1      Farming                  8      4424     321 PiB       3h 43m    
tad                  1.0.2           Farming                 34      4424     301 PiB       3h 17m  


--------------------------------------------- HARVESTERS ---------------------------------------------------
                                                                                     Longest        Longest        
                                                                          Last      Response       Response       
Fork                 Version         Status            # Plots         Harvest         Today      Yesterday      
------------------------------------------------------------------------------------------------------------
apple                1.2.31.dev1     Harvesting           1379          1s ago         2.72s          2.51s
avocado              1.1.7.dev124    Harvesting           1379          7s ago         2.36s          2.76s
btcgreen             2.1.0           Harvesting           1379          7s ago         1.73s          3.33s
cactus               1.2.2.dev7      Harvesting           1379          4s ago         1.83s          3.48s
cannabis             1.2.301         Harvesting           1379          4s ago         2.46s          3.55s
chia                 1.2.5           Harvesting           1379          3s ago         3.60s          3.11s
covid                1.2.3           Harvesting           1379          6s ago         2.57s          2.93s
cryptodoge           1.2.6           Harvesting           1379          6s ago         2.43s          2.58s
dogechia             1.0.9           Harvesting           1379          3s ago         2.67s          3.58s
flax                 0.1.1           Harvesting           1379          8s ago         2.04s          2.85s
flora                0.2.5           Harvesting           1379          9s ago         2.07s          2.40s
goji                 0.2.3           Harvesting           1379          6s ago         2.62s          2.98s
greendoge            1.2.5.dev2      Harvesting           1379          2s ago         2.49s          3.41s
```

**Comment by bithadder** [comment]
excited~ I can't wait to try those.

**Comment by bithadder** [comment]
thanks a lot
